language: python
sudo: enabled
dist: xenial
group: edge

python:
  - "3.7"

install:
  #https://www.slimjet.com/chrome/google-chrome-old-version.php
  - wget -N "https://www.slimjet.com/chrome/download-chrome.php?file=files%2F79.0.3945.88%2Fgoogle-chrome-stable_current_amd64.deb" -O ~/google-chrome-stable_current_amd64.deb
  - sudo apt install -y ~/google-chrome-stable_current_amd64.deb
  - echo $(google-chrome --version)
  - wget -N "https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip" -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - echo $(/usr/local/bin/chromedriver -v)
  - sudo apt-get install -y xvfb xclip
  - pip3 install -r $TRAVIS_BUILD_DIR/ui_testing/requirements.txt

script:
  - export TESTS='test09_my_profile.py:'
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export TESTS=''; fi
  - cd $TRAVIS_BUILD_DIR && export PYTHONPATH='./'
  - xvfb-run -a nosetests-3.4 -vs --logging-level=WARNING ui_testing/testcases/basic_tests/test02_articles.py:ArticlesTestCases.test004_cancel_button_edit_comment_1_cancel --tc-file=config.ini
  - xvfb-run -a nosetests-3.4 -vs --logging-level=WARNING ui_testing/testcases/basic_tests/test03_testplans.py:TestPlansTestCases.test001_test_plan_delete_testunit --tc-file=config.ini
  - xvfb-run -a nosetests-3.4 -vs --logging-level=WARNING ui_testing/testcases/basic_tests/test04_testunits.py:TestUnitsTestCases.test006_search_by_archived_testunit --tc-file=config.ini
  - xvfb-run -a nosetests-3.4 -vs --logging-level=WARNING ui_testing/testcases/basic_tests/test05_contacts.py:ContactsTestCases.test_003_create_contact --tc-file=config.ini
  - xvfb-run -a nosetests-3.4 -vs --logging-level=WARNING ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test002_cancel_button_edit_contact_0_save_btn --tc-file=config.ini
  - xvfb-run -a nosetests-3.4 -vs --logging-level=WARNING ui_testing/testcases/header_tests/test06_audit_trail.py:AuditTrailTestCases.test003_search_audit_trail_1_action --tc-file=config.ini
  - xvfb-run -a nosetests-3.4 -vs --logging-level=WARNING ui_testing/testcases/header_tests/test08_usermanagement.py:HeaderTestCases.test001_archive_user_management --tc-file=config.ini
  - xvfb-run -a nosetests-3.4 -vs --logging-level=WARNING ui_testing/testcases/header_tests/test09_my_profile.py:MyProfileTestCases.test001_user_can_change_password_and_press_on_cancel --tc-file=config.ini
  - xvfb-run -a nosetests-3.4 -vs --logging-level=WARNING ui_testing/testcases/header_tests/test09_rolesandpermissions.py:HeaderTestCases.test001_archive_roles_and_permissions --tc-file=config.ini
