language: python
sudo: enabled
dist: trusty
group: edge

python:
  - "3.5"

addons:
  chrome: stable
install:
  - wget -N https://chromedriver.storage.googleapis.com/75.0.3770.90/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - sudo apt-get install -y xvfb xclip
  - pip3 install -r $TRAVIS_BUILD_DIR/ui_testing/requirements.txt

script:

  - export TESTS='test04_testunits.py'
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export TESTS=''; fi
  - echo $TESTS
  - cd $TRAVIS_BUILD_DIR && export PYTHONPATH='./'
  - xvfb-run -a nosetests-3.4 -vs --nologcapture ui_testing/testcases/basic_tests/$TESTS --tc-file=config.ini
