language: python
sudo: enabled
dist: xenail
group: edge

python:
  - "3.5"

install:
  #https://www.slimjet.com/chrome/google-chrome-old-version.php
  - wget -N "https://www.slimjet.com/chrome/download-chrome.php?file=files%2F79.0.3945.88%2Fgoogle-chrome-stable_current_amd64.deb" -O ~/google-chrome-stable_current_amd64.deb
  - sudo apt install -y ~/google-chrome-stable_current_amd64.deb
  - echo $(google-chrome --version)
  - wget -N "https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip" -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - echo $(/usr/bin/chromedriver -v)
  - sudo apt-get install -y xvfb xclip
  - pip3 install -r $TRAVIS_BUILD_DIR/ui_testing/requirements.txt

script:

  - export TESTS='test08_usermanagement.py:'
  #- export TESTS='test04_testunits.py:TestUnitsTestCases.test011_create_test_unit_with_random_category'
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export TESTS=''; fi
  #- echo $TESTS
  - cd $TRAVIS_BUILD_DIR && export PYTHONPATH='./'
  - xvfb-run -a nosetests-3.4 -vs --logging-level=WARNING ui_testing/testcases/header_tests/test06_audit_trail.py:AuditTrailTestCases.test003_search_audit_trail_0_changed_by --tc-file=config.ini
  - xvfb-run -a nosetests-3.4 -vs --logging-level=WARNING ui_testing/testcases/header_tests/test06_audit_trail.py:AuditTrailTestCases.test003_search_audit_trail_1_action --tc-file=config.ini
  - xvfb-run -a nosetests-3.4 -vs --logging-level=WARNING ui_testing/testcases/header_tests/test06_audit_trail.py:AuditTrailTestCases.test003_search_audit_trail_2_entity --tc-file=config.ini
  - xvfb-run -a nosetests-3.4 -vs --logging-level=WARNING ui_testing/testcases/header_tests/test06_audit_trail.py:AuditTrailTestCases.test003_search_audit_trail_3_entity_number --tc-file=config.ini