language: python
sudo: enabled
dist: xenial
group: edge

services:
  - docker

before_script:
  - docker build -t selenium:lims $TRAVIS_BUILD_DIR/ --no-cache

script:
  - export TESTS='test08_usermanagement.py:'
  #- export TESTS='test04_testunits.py:TestUnitsTestCases.test011_create_test_unit_with_random_category'
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export TESTS=''; fi
  - cd $TRAVIS_BUILD_DIR && export PYTHONPATH='./'
  - export LOGURU_LEVEL='INFO'
  - xvfb-run -a nosetests -vs --nologcapture --tc-file=config.ini --with-flaky --force-flaky --max-runs=3 --min-passes=1 -m 'test[0-9]{3}' ui_testing/testcases/basic_tests/test04_testunits.py:TestUnitsTestCases
  - docker run -t --shm-size=2g -v $TRAVIS_BUILD_DIR:/1lims-automation selenium:lims bash -c "./run.sh"
