name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        test_cases: ["ui_testing/testcases/header_tests/test09_my_profile.py:MyProfileTestCases.test007_my_profile_user_can_upload_logo",
                     "ui_testing/testcases/header_tests/test09_my_profile.py:MyProfileTestCases.test008_my_profile_user_can_update_logo",
                     "ui_testing/testcases/header_tests/test09_my_profile.py:MyProfileTestCases.test009_you_cant_upload_more_than_one_logo"]

    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run:  pip3 install -r requirements.txt
      - name: Execute test case
        run: |
          export PYTHONPATH='$PYTHONPATH:./'
          script -e -c $'xvfb-run -a ~/.local/bin/nosetests-3.4 -vs --nologcapture --tc-file=config.ini ${{ matrix.test_cases }}'
