name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        test_cases: ["ui_testing/testcases/basic_tests/test03_testplans.py:TestPlansTestCases.test003_archive_test_plan_one_record"]

    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run:  pip3 install --upgrade setuptools pip && pip3 install -r requirements.txt
      - name: Execute test case
        run: |
          export PYTHONPATH='$PYTHONPATH:./'
          script -e -c $'xvfb-run -a ~/.local/bin/nosetests-3.4 -vs --nologcapture --tc-file=config.ini ${{ matrix.test_cases }}'
      - name: Start SSH via Ngrok
        if: ${{ failure() }}
        run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        env:
         NGROK_TOKEN: 1TmHkDZqdgfk4nKtBfmZT8RcYAK_25q7iVJ4QsPazz1y5ftcz
         USER_PASS: 0xislamtaha
      - name: Don't kill instace
        if: ${{ failure() }}
        run: sleep 1h # Prevent to killing instance after failure
