# name: CI
#
# on:
#   pull_request:
#     branches: [ master ]
#
# jobs:
#   test_pull_request_in_parallel:
#     runs-on: ubuntu-20.04
#     strategy:
#       fail-fast: false
#       matrix:
#         test_cases: [0]
#
#     steps:
#       - uses: actions/checkout@master
#
#       - name: pull docker image
#         run:  docker pull 0xislamtaha/seleniumchromenose:83
#
#       - name: parallel execution for each module
#         run: timeout 2h bash .github/workflows/execution.sh ${{ strategy.job-total }} ${{ matrix.test_cases }} ${{ github.ref }} ${{ github.run_id }} ${{ github.run_number }} $(pwd) 'not series' ${{ secrets.UUID }}
