name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request_in_parallel:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        test_cases: [0, 1, 2, 3]

    steps:
      - uses: actions/checkout@master
      - name: pull docker image
        run:  docker pull 0xislamtaha/seleniumchromenose:83
      - name: execute test case in parallel
        env:
          TEST_FILE: ui_testing/testcases/header_tests/test09_rolesandpermissions.py
          TEST_REG: test[0-9]{3}
        run: docker container run -t --shm-size=2g -v `pwd`:/1lims-automation -e "PYTHONPATH='$PYTHONPATH:/1lims-automation" -w /1lims-automation 0xislamtaha/seleniumchromenose:83 bash -c "NODE_TOTAL=4 NODE_INDEX=${{ matrix.test_cases }} nosetests -vs --nologcapture --tc-file=config.ini --tc=browser.headless:True  --with-flaky --force-flaky --max-runs=3 --min-passes=1 --with-parallel -A 'not series' -m '$TEST_REG' $TEST_FILE"

  test_pull_request_in_series:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@master
      - name: pull docker image
        run:  docker pull 0xislamtaha/seleniumchromenose:83
      - name: execute test case in series
        env:
          TEST_FILE: ui_testing/testcases/header_tests/test09_rolesandpermissions.py
          TEST_REG: test[0-9]{3}
        run: docker container run -t --shm-size=2g -v `pwd`:/1lims-automation -e "PYTHONPATH='$PYTHONPATH:/1lims-automation" -w /1lims-automation 0xislamtaha/seleniumchromenose:83 bash -c "nosetests -vs --nologcapture --tc-file=config.ini --tc=browser.headless:True  --with-flaky --force-flaky --max-runs=3 --min-passes=1 --with-parallel -A 'series' -m '$TEST_REG' $TEST_FILE"