name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request_in_parallel:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        test_cases: [0, 1]

    steps:
      - uses: actions/checkout@master

      - name: pull docker image
        run:  docker pull 0xislamtaha/seleniumchromenose:83

      - name: execute test case in parallel
        env:
          TEST_FILE: ui_testing/testcases/basic_tests/test05_contacts.py
          TEST_REG: test02[2-3]{1}
