name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run:  docker build -t selenium:lims ./ --no-cache
      - name: Execute test case
        run: docker run -t --shm-size=2g -v `pwd`:/1lims-automation selenium:lims bash -c "./run.sh"

#      - name: Start SSH via Ngrok
#        if: ${{ failure() }}
#        run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
#        env:
#         NGROK_TOKEN: 1TmHkDZqdgfk4nKtBfmZT8RcYAK_25q7iVJ4QsPazz1y5ftcz
#         USER_PASS: 0xislamtaha
#      - name: Don't kill instace
#        if: ${{ failure() }}
#        run: sleep 1h # Prevent to killing instance after failure
