---
jobs:
  test_pull_request:
    runs-on: ubuntu-20.04
    steps:
      -
        uses: actions/checkout@master
      -
        name: "pull docker image"
        run: "docker pull 0xislamtaha/seleniumchromenose:83"
      -
        env:
          TEST_FILE: ui_testing/testcases/basic_tests/test04_testunits.py
          TEST_REG: "test[0-9]{3}"
          run: "docker container run -t --shm-size=2g -v `pwd`:/1lims-automation -e \"PYTHONPATH='$PYTHONPATH:/1lims-automation\" -w /1lims-automation 0xislamtaha/seleniumchromenose:83 bash -c \"NODE_TOTAL=4 NODE_INDEX=${{ matrix.test_cases }} nosetests -a parallel='false'"
        name: "Execute test case"
    strategy:
      fail-fast: false
      matrix:
        test_cases:
          - 0
          - 1
          - 2
          - 3
name: CI
true:
  pull_request:
    branches:
      - master
