name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        test_cases: ["ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test042_Duplicate_sub_order_with_multiple_testplans_and_testunits_add_approach"]

    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run:  pip3 install -r requirements.txt
      - name: Execute test case
        run: |
          export PYTHONPATH='$PYTHONPATH:./'
          script -e -c $'xvfb-run -a ~/.local/bin/nosetests-3.4 -vs --nologcapture --tc-file=config.ini ${{ matrix.test_cases }}'
