name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request_in_parallel:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        test_cases: ["ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test042_Duplicate_or_update_order_with_test_plan_only"]

    steps:
      - uses: actions/checkout@master

      - name: pull docker image
        run:  docker pull 0xislamtaha/seleniumchromenose:83
      - name: execute test case
        run: docker container run -t --shm-size=2g -v `pwd`:/1lims-automation -e "PYTHONPATH='$PYTHONPATH:/1lims-automation" -w /1lims-automation 0xislamtaha/seleniumchromenose:83 bash -c "NODE_TOTAL=${{ strategy.job-total }} NODE_INDEX=${{ matrix.test_cases }} nosetests -vs --nologcapture --tc-file=config.ini --tc=browser.headless:True  --with-flaky --force-flaky --max-runs=3 --min-passes=1 --with-parallel -A 'not series' -m '$TEST_REG' $TEST_FILE"

